name: rpg_companion
description: "RPG Companion Flutter app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.12.0
  markdown: ^7.2.2
  http: ^1.2.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  anvil_foundry:
    path: ../../../Github/anvil_foundry

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
